### ISSUE TITLE
Devuelveme el nombre del cliente en el grid de facturacion y conduce no el id.

### ISSUE THREAD

**Issue by ricardomalagon** [KeltDevelopments/DairiesFoods#24]

**Comment by ricardomalagon** [comment]
No dejes de traer el id, porque se va utilizar.

**Comment by jamyrcarrasco** [comment]
![image](https://user-images.githubusercontent.com/33583213/75308666-67feaf80-5825-11ea-8cdc-bcc01c54d927.png)
