### ISSUE TITLE
Hazme el metodo de todo el detalle de la factura para poder imprimirla.

### ISSUE THREAD

**Issue by ricardomalagon** [KeltDevelopments/DairiesFoods#25]
Que te envie el id y me traigas toda la informacion.

**Comment by jamyrcarrasco** [comment]
http://127.0.0.1:8000/api/sales/getSalesDetail?id=971

**Comment by jamyrcarrasco** [comment]
![image](https://user-images.githubusercontent.com/33583213/75307773-f4f43980-5822-11ea-834e-b669683d278f.png)
