### ISSUE TITLE
Crear api para cambiar el estado y traer todos los estados de la factura con su codigo y label.

### ISSUE THREAD

**Issue by ricardomalagon** [KeltDevelopments/DairiesFoods#30]
Estados:
Pendiente por pagar
Pagada
Vencida
Anulada

**Comment by jamyrcarrasco** [comment]
![image](https://user-images.githubusercontent.com/33583213/75831694-88c98680-5d8a-11ea-9339-4ca391943e87.png)

**Comment by jamyrcarrasco** [comment]
![image](https://user-images.githubusercontent.com/33583213/75831714-9b43c000-5d8a-11ea-94b7-206d83856658.png)

**Comment by jamyrcarrasco** [comment]
http://127.0.0.1:8000/api/sales/updateSaleStatus?saleId=981&status=SL002
