### ISSUE TITLE
Hacer reportes de ventas

### ISSUE THREAD

**Issue by ricardomalagon** [KeltDevelopments/DairiesFoods#58]
- Por tipo de comprobante
- Por fecha
- Por cliente
- Por producto

**Comment by jamyrcarrasco** [comment]
![image](https://user-images.githubusercontent.com/33583213/78465720-2afcc700-76c7-11ea-93e4-bcd051c919b6.png)

**Comment by jamyrcarrasco** [comment]
Los parametros van por la URL. si se te dificulta ponerlos todos ahi tambien puedes armar un objeto y mandarlo.

**Comment by jamyrcarrasco** [comment]
![image](https://user-images.githubusercontent.com/33583213/78847766-b59e3880-79dd-11ea-813b-d4b3152808c2.png)
Agregue aqui un rango de fecha para la busqueda de ventas. Con el un total de lo vendido dentro de ese rango
